# --- LISTA DE CÓDIGOS PRESTACIONALES CATEGORIZADA Y ACTUALIZADA ---
CODIGOS_PRESTACIONALES_CATEGORIZADOS = [
    # POR ASIGNAR
    {"categoria": "POR ASIGNAR", "codigo": "301", "descripcion": "Cuidado Integral de salud del Niño"},
    {"categoria": "POR ASIGNAR", "codigo": "302", "descripcion": "Cuidado Integral de salud del Adolescente"},
    {"categoria": "POR ASIGNAR", "codigo": "303", "descripcion": "Cuidado Integral de salud del Joven"},
    {"categoria": "POR ASIGNAR", "codigo": "304", "descripcion": "Cuidado Integral de salud del Adulto"},
    {"categoria": "POR ASIGNAR", "codigo": "305", "descripcion": "Cuidado Integral de salud del Adulto Mayor"},
    {"categoria": "POR ASIGNAR", "codigo": "306", "descripcion": "Cuidado Integral de salud Prenatal"},
    # ACTIVIDAD PREVENTIVA
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "002", "descripcion": "Control del recién nacido con menos de 2,500 gr, prematuro, con secuelas al nacer"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "029", "descripcion": "Tamizaje Neonatal"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "001", "descripcion": "Control de crecimiento y desarrollo en menores entre 0 - 4 años"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "118", "descripcion": "Control de crecimiento y desarrollo en menores entre 5 - 9 años"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "119", "descripcion": "Control de crecimiento y desarrollo en entre de 10 - 11 años"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "016", "descripcion": "Atención temprana para menores de 36 meses"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "007", "descripcion": "Suplemento de micronutrientes"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "005", "descripcion": "Consejería nutricional para niñas o niños en riesgo nutricional y desnutrición"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "008", "descripcion": "Profilaxis antiparasitaria"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "019", "descripcion": "Detección trastorno agudeza visual y ceguera"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "017", "descripcion": "Atención Integral del adolescente"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "020", "descripcion": "Salud Bucal"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "021", "descripcion": "Prevencion de caries"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "022", "descripcion": "Detección de problemas en Salud Mental"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "009", "descripcion": "Atención prenatal"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "010", "descripcion": "Atención del puerperio normal"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "011", "descripcion": "Exámenes de laboratorio completo de la gestante"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "023", "descripcion": "Deteccion precoz de cancer de prostata (PSA)"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "025", "descripcion": "Detección precoz de cancer de mama (Mamografía)"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "013", "descripcion": "Exámenes de ecografía obstétrica"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "015", "descripcion": "Diagnóstico del embarazo"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "024", "descripcion": "Detección precoz de cáncer cérvico-uterino"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "018", "descripcion": "Salud reproductiva (planificación familiar)"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "902", "descripcion": "Atención Preconcepcional"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "903", "descripcion": "Atenciòn Integral de Salud del Adulto Mayor"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "904", "descripcion": "Atención Integral de Salud del Joven y Adulto"},
    {"categoria": "ACTIVIDAD PREVENTIVA", "codigo": "911", "descripcion": "Instrucción de Higiene Oral y Asesoría nutricional para el control de enfermedades dentales"},
    # ACTIVIDAD RECUPERATIVA
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "050", "descripcion": "Atención inmediata del recién nacido normal"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "051", "descripcion": "Internamiento del RN con patología no quirurgica"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "052", "descripcion": "Internamiento con intervención quirúrgica del RN"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "054", "descripcion": "Atención de parto vaginal"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "055", "descripcion": "Cesárea"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "906", "descripcion": "Consulta externa por profesionales no médicos ni odontólogos"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "056", "descripcion": "Consulta externa"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "057", "descripcion": "Obturación y curación dental simple"},
    {"categoria": "ACTIVIDAD RECUPERativa", "codigo": "058", "descripcion": "Obturación y curación dental compuesta"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "059", "descripcion": "Extracción dental (exodoncia)"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "060", "descripcion": "Atención extramural urbana y periurbana (Visita domiciliaria)"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "075", "descripcion": "Atención extramural rural (Visita domiciliaria)"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "061", "descripcion": "Atención en tópico"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "062", "descripcion": "Atención por emergencia"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "063", "descripcion": "Atención por emergencia con observación"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "064", "descripcion": "Intervención medico-quirúrgica ambulatoria"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "065", "descripcion": "Internamiento en EESS sin intervención quirúrgica"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "066", "descripcion": "Internamiento con intervención quirúrgica menor"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "067", "descripcion": "Internamiento con intervención quirúrgica mayor"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "068", "descripcion": "Internamiento con Estancia en la Unidad de Cuidados Intensivos (UCI)"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "069", "descripcion": "Transfusión sanguínea o hemoderivados"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "070", "descripcion": "Atención odontológica especializada"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "027", "descripcion": "Tratamiento profilactico a niños expuestos al VIH"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "053", "descripcion": "Tratamiento de VIH-SIDA (0-19a)"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "074", "descripcion": "Prevención, detección y tratamiento de ITS en adolescentes, jóvenes, adultos y adultos mayores"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "S01", "descripcion": "(****) Complementario"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "026", "descripcion": "Tratamiento profiláctico para gestante positiva a prueba rápida/ELISA VIH"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "071", "descripcion": "Apoyo al diagnóstico"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "901", "descripcion": "Apoyo al Tratamiento"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "908", "descripcion": "Atención domiciliaria"},
    {"categoria": "ACTIVIDAD RECUPERATIVA", "codigo": "300", "descripcion": "Telemedicina"},
    # REHABILITACION
    {"categoria": "REHABILITACION", "codigo": "200", "descripcion": "Atención de rehabilitación"},
    {"categoria": "REHABILITACION", "codigo": "900", "descripcion": "Prótesis dental removible"},
    # PRESTACION ADMINISTRATIVA
    {"categoria": "PRESTACION ADMINISTRATIVA", "codigo": "111", "descripcion": "Asignación por Alimentación"},
    {"categoria": "PRESTACION ADMINISTRATIVA", "codigo": "117", "descripcion": "Traslado de Emergencia"},
    {"categoria": "PRESTACION ADMINISTRATIVA", "codigo": "112", "descripcion": "Sepelio para Óbito fetal (Muerte Intraútero)"},
    {"categoria": "PRESTACION ADMINISTRATIVA", "codigo": "116", "descripcion": "Sepelio para Recién Nacidos"},
    {"categoria": "PRESTACION ADMINISTRATIVA", "codigo": "113", "descripcion": "Sepelio para Niñas/os"},
    {"categoria": "PRESTACION ADMINISTRATIVA", "codigo": "114", "descripcion": "Sepelio para Adolescentes y Adultos"},
]

